# Generated by Django 5.2.1 on 2025-05-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BronxNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_uuid', models.UUIDField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.CharField(max_length=255)),
                ('snippet', models.TextField()),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('categories', models.JSONField()),
            ],
        ),
    ]
