# Generated by Django 5.2.1 on 2025-05-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learning_path_title',
            field=models.CharField(max_length=300),
        ),
    ]
