# Generated by Django 5.2.1 on 2025-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_course_learning_path_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
