# Generated by Django 5.2.1 on 2025-05-23 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_enrolledcourse_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('type', models.CharField(choices=[('welfare', 'Welfare'), ('skills', 'Skills')], max_length=50)),
            ],
        ),
    ]
