# Generated by Django 5.2.1 on 2025-05-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_resourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcontent',
            name='atempt_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
