# Generated by Django 5.2.1 on 2025-05-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_quizcontent_atempt_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizcontent',
            old_name='atempt_number',
            new_name='attempt_number',
        ),
    ]
