# Generated by Django 5.2.1 on 2025-05-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_rename_atempt_number_quizcontent_attempt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learning_path_title',
            field=models.CharField(choices=[('Adolescent Pregnancy Prevention', 'Adolescent Pregnancy Prevention'), ('Youth Crime & Gang Prevention', 'Youth Crime & Gang Prevention'), ('Legal Literacy & Civic Education', 'Legal Literacy & Civic Education')], max_length=300),
        ),
    ]
