# Generated by Django 5.2.1 on 2025-05-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_course_learning_path_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content_title',
            field=models.CharField(max_length=300),
        ),
    ]
