# Generated by Django 5.2.1 on 2025-05-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_course_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcontent',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
