# Generated by Django 5.2.1 on 2025-05-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseusermodel',
            name='invited_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
